import {
  ActivityLogEntity,
  AttachmentEntity,
  BoardEntity,
  CommentEntity,
  CustomFieldDefinitionEntity,
  ImportJobEntity,
  ImportRecordEntity,
  IssueEntity,
  IssueLinkEntity,
  IssueTypeEntity,
  NotificationEntity,
  ProjectEntity,
  ProjectIssueTypeEntity,
  ProjectMemberEntity,
  ProjectPluginEntity,
  RoleEntity,
  SavedFilterEntity,
  SprintEntity,
  TimeEntryEntity,
  WebhookEntity,
  WorkflowEntity,
  WorkflowStatusEntity,
  WorkflowTransitionEntity,
} from './entities/tenant';

export const TENANT_ENTITIES = [
  ProjectEntity,
  ProjectMemberEntity,
  ProjectIssueTypeEntity,
  IssueEntity,
  IssueTypeEntity,
  IssueLinkEntity,
  WorkflowEntity,
  WorkflowStatusEntity,
  WorkflowTransitionEntity,
  BoardEntity,
  SprintEntity,
  CommentEntity,
  ActivityLogEntity,
  RoleEntity,
  CustomFieldDefinitionEntity,
  NotificationEntity,
  WebhookEntity,
  SavedFilterEntity,
  TimeEntryEntity,
  AttachmentEntity,
  ProjectPluginEntity,
  ImportJobEntity,
  ImportRecordEntity,
] as const;
