apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaver.fullname" . }}-api
  labels:
    {{- include "weaver.labels" . | nindent 4 }}
    {{- include "weaver.api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "weaver.api.selectorLabels" . | nindent 4 }}
