apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weaver.fullname" . }}-config
  labels:
    {{- include "weaver.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ include "weaver.postgresql.host" . | quote }}
  DATABASE_PORT: "5432"
  DATABASE_NAME: {{ .Values.postgresql.auth.database | quote }}
  DATABASE_USER: {{ .Values.postgresql.auth.username | quote }}
  REDIS_HOST: {{ include "weaver.redis.host" . | quote }}
  REDIS_PORT: "6379"
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  WEAVER_TRUSTED_PLUGINS: {{ .Values.env.WEAVER_TRUSTED_PLUGINS | quote }}
  STORAGE_LOCAL_PATH: "/tmp/weaver-uploads"
