apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaver.fullname" . }}-secrets
  labels:
    {{- include "weaver.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.env.JWT_SECRET | b64enc | quote }}
