apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaver.fullname" . }}-secrets
  labels:
    {{- include "weaver.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.env.JWT_SECRET | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.env.GITHUB_CLIENT_ID | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.env.GITHUB_CLIENT_SECRET | b64enc | quote }}
