apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: weaver
spec:
  replicas: null
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
